//------------------------------------------------------------------------------
// @file       country_data.h
// @author     Matthew Hird
// @date       April 1, 2018
//
// @brief      The main function for the program pex5.
//------------------------------------------------------------------------------

#pragma once
#include <iostream>


class CountryData
{
public:
    /**
     * @brief      Default constructor.
     */
    CountryData();
    

    /**
     * @brief      Parameterized constructor.
     *
     * @param[in]  c_name  Initializes 'name' member variable.
     */
    CountryData(std::string c_name);
    

    /**
     * @brief      Copy constructor.
     *
     * @param[in]  other  The CountryData object to be copied.
     */
    CountryData(const CountryData& other);
    

    /**
     * @brief      Deconstructor.
     */
    ~CountryData();


    /**
     * @brief      Overloads >> operator of istream objects. Streams data in a
     *             specific format into member variables. Use to load
     *             CountryData object from a string or .txt file. Can read data
     *             generated by overloaded ostream operator <<. See
     *             country_data.cpp for implementation details.
     *
     * @param      istr  The istream left operand of >>.
     * @param      data  The CountryData right operand being streamed into.
     *
     * @return     A reference to the istream object. Used to string together
     *             multiple >> operations in a single expression.
     */
    friend std::istream& operator>>(std::istream& istr, CountryData& data);
    

    /**
     * @brief      Overloads << operator of ostream objects. Streams data from
     *             CountryData object's member variables into a string or .txt
     *             file. Data written by this operation can be read by
     *             overloaded istream operator >>. See country_data.cpp for
     *             implementation details.
     *
     * @param      ostr  The ostream left operand of <<.
     * @param[in]  data  The CountryData right operand whose member variables
     *                   are being streamed.
     *
     * @return     A reference to the ostream object. Used to string together
     *             multiple << operations in a single expression.
     */
    friend std::ostream& operator<<(std::ostream& ostr, const CountryData& data);

    
    /**
     * @brief      Sets the name member variable.
     *
     * @param[in]  c_name  The name value.
     */
    void set_name(std::string c_name);
    

    /**
     * @brief      Sets the capital member variable.
     *
     * @param[in]  cap   The capital value.
     */
    void set_capital(std::string cap);
    

    /**
     * @brief      Sets the language member variable.
     *
     * @param[in]  lang  The language value.
     */
    void set_language(std::string lang);
    

    /**
     * @brief      Sets the area member variable.
     *
     * @param[in]  c_area  The area value (in square kilometers).
     */
    void set_area(double c_area);
    

    /**
     * @brief      Sets the population member variable.
     *
     * @param[in]  pop   The population value (number of people).
     */
    void set_population(long int pop);
    

    /**
     * @brief      Sets the description member variable.
     *
     * @param[in]  descript  The description value.
     */
    void set_description(std::string descript);


    /**
     * @brief      Gets the name member variable.
     *
     * @return     The name value.
     */
    std::string get_name() const;
    

    /**
     * @brief      Gets the capital member variable.
     *
     * @return     The capital value.
     */
    std::string get_capital() const;
    

    /**
     * @brief      Gets the language member variable.
     *
     * @return     The language value.
     */
    std::string get_language() const;
    

    /**
     * @brief      Gets the area member variable.
     *
     * @return     The area value (in square kilometers).
     */
    double get_area() const;
    

    /**
     * @brief      Gets the population member variable.
     *
     * @return     The population value (number of people).
     */
    long int get_population() const;
    

    /**
     * @brief      Gets the description member variable.
     *
     * @return     The description value.
     */
    std::string get_description() const;

private:
    std::string name;
    std::string capital;
    std::string language;
    double area;
    long population;
    std::string description;
};